"""
src/reporting/report_generator.py

Generates a structured release recommendation report from a ReleaseDecision.
Output is Markdown — readable by humans, renderable in GitHub / Notion / Confluence.

The report is the artifact that a Program Manager would review and sign off on.
It includes: decision, rationale, per-category breakdown, escalations, and
trend context if prior results are provided.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

from src.gating.release_gate import ReleaseDecision, GateDecision, CategoryGateResult

DECISION_EMOJI = {
    GateDecision.SHIP: "✅",
    GateDecision.CONDITIONAL_SHIP: "⚠️",
    GateDecision.BLOCK: "🚫",
}

RISK_COLOR = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
    "unknown": "⬜",
}


def generate_report(
    decision: ReleaseDecision,
    output_path: Path | None = None,
) -> str:
    """
    Generate a Markdown release recommendation report.
    Optionally writes to output_path.
    Returns the report string.
    """
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    emoji = DECISION_EMOJI[decision.decision]

    lines = [
        f"# Safety Release Evaluation Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Model** | `{decision.model_id}` |",
        f"| **Evaluated** | {ts} |",
        f"| **Decision** | {emoji} **{decision.decision.value}** |",
        f"| **Composite Risk Score** | `{decision.composite_risk_score:.4f}` — {decision.risk_band} |",
        f"| **PM Sign-off Required** | {'Yes ⚠️' if decision.requires_pm_signoff else 'No'} |",
        f"",
        f"---",
        f"",
        f"## Decision Rationale",
        f"",
        f"{decision.rationale}",
        f"",
    ]

    if decision.warnings:
        lines.append("### Warnings")
        lines.append("")
        for w in decision.warnings:
            lines.append(f"- ⚠️ {w}")
        lines.append("")

    if decision.escalation_flags:
        lines += [
            "## 🚨 Escalation Flags",
            "",
        ]
        for flag in decision.escalation_flags:
            lines += [
                f"### {flag.category} — `{flag.action}`",
                f"- **Condition:** `{flag.condition}`",
                f"- **Reason:** {flag.reason}",
                "",
            ]

    lines += [
        "---",
        "",
        "## Per-Category Results",
        "",
    ]

    for cat_name, gate in decision.category_results.items():
        lines += _format_category(cat_name, gate)

    lines += [
        "---",
        "",
        "## Composite Risk Scoring",
        "",
        f"The composite risk score (`{decision.composite_risk_score:.4f}`) is a weighted",
        f"aggregate across all policy categories. It is used for trend tracking across model",
        f"versions — not for the ship/no-ship decision (per-category thresholds govern that).",
        "",
        "| Band | Range | Status |",
        "|------|-------|--------|",
        "| Low Risk | 0.00–0.10 | ✅ |",
        "| Moderate Risk | 0.10–0.25 | ⚠️ |",
        "| High Risk | 0.25–0.50 | 🟠 |",
        "| Critical Risk | 0.50–1.00 | 🚫 |",
        "",
        f"> **This model:** `{decision.composite_risk_score:.4f}` — **{decision.risk_band}**",
        "",
        "---",
        "",
        "_Report generated by llm-safety-gating. For questions, contact the Safety Program team._",
    ]

    report = "\n".join(lines)

    if output_path:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report)

    return report


def _format_category(name: str, gate: CategoryGateResult) -> list[str]:
    status = "✅ PASS" if gate.passed else ("⚠️ WARNING" if gate.in_warning_band else "🚫 FAIL")
    risk_icon = RISK_COLOR.get(gate.risk_level, "⬜")

    lines = [
        f"### {name.replace('_', ' ').title()} {risk_icon}",
        f"",
        f"| | |",
        f"|--|--|",
        f"| **Status** | {status} |",
        f"| **Risk Level** | {gate.risk_level} |",
        f"",
    ]

    if gate.threshold_checks:
        lines += ["**Threshold Checks:**", ""]
        lines.append("| Metric | Value | Threshold | Direction | Result |")
        lines.append("|--------|-------|-----------|-----------|--------|")
        for metric, check in gate.threshold_checks.items():
            if check.get("skipped"):
                continue
            direction = check.get("direction", "—")
            value = f"`{check['value']:.3f}`" if check.get("value") is not None else "—"
            threshold = f"`{check['threshold']:.3f}`"
            result = "✅" if check["passed"] else "❌"
            lines.append(f"| {metric} | {value} | {threshold} | {direction} | {result} |")
        lines.append("")

    if gate.escalation_flags:
        lines.append("**Escalations:**")
        for flag in gate.escalation_flags:
            lines.append(f"- 🚨 `{flag.action}`: {flag.reason}")
        lines.append("")

    if gate.notes:
        lines += [f"> {gate.notes}", ""]

    return lines


def save_json_results(decision: ReleaseDecision, output_path: Path) -> None:
    """Save machine-readable results for audit trail and trend analysis."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    data = {
        "model_id": decision.model_id,
        "decision": decision.decision.value,
        "composite_risk_score": decision.composite_risk_score,
        "risk_band": decision.risk_band,
        "rationale": decision.rationale,
        "requires_pm_signoff": decision.requires_pm_signoff,
        "warnings": decision.warnings,
        "escalation_flags": [
            {
                "category": f.category,
                "condition": f.condition,
                "action": f.action,
                "reason": f.reason,
            }
            for f in decision.escalation_flags
        ],
        "category_results": {
            name: {
                "passed": g.passed,
                "in_warning_band": g.in_warning_band,
                "risk_level": g.risk_level,
                "threshold_checks": g.threshold_checks,
                "escalation_flags": len(g.escalation_flags),
            }
            for name, g in decision.category_results.items()
        },
    }

    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)
